thing-zoo/algorithm-study

- BOJ/seeun/week_3/BFS, DFS/10026_적록색약.py
- BOJ/seeun/week_3/BFS, DFS/1012_유기농 배추.py
- BOJ/seeun/week_3/BFS, DFS/13549_숨바꼭질 3.py
- BOJ/seeun/week_3/BFS, DFS/14442_벽 부수고 이동하기 2.py
- BOJ/seeun/week_3/BFS, DFS/1600_말이 되고픈 원숭이.py
- BOJ/seeun/week_3/BFS, DFS/1697_숨바꼭질.py
- BOJ/seeun/week_3/BFS, DFS/1926_그림.py
- BOJ/seeun/week_3/BFS, DFS/2178_미로 탐색.py
- BOJ/seeun/week_3/BFS, DFS/2206_벽 부수고 이동하기.py
- BOJ/seeun/week_3/BFS, DFS/2468_안전 영역.py
- BOJ/seeun/week_3/BFS, DFS/2573_빙산.py
- BOJ/seeun/week_3/BFS, DFS/2583_영역 구하기.py
- BOJ/seeun/week_3/BFS, DFS/2667_단지번호붙이기.py
- BOJ/seeun/week_3/BFS, DFS/5014_스타트링크.py
- BOJ/seeun/week_3/BFS, DFS/6593_상범 빌딩.py
- BOJ/seeun/week_3/BFS, DFS/7562_나이트의 이동.py
- BOJ/seeun/week_3/BFS, DFS/7569_토마토.py
- BOJ/seeun/week_3/BFS, DFS/7576_토마토.py
- BOJ/seeun/week_3/BFS, DFS/9466_텀프로젝트.py
- PGS/seeun/week_3/BFS, DFS/게임 맵 최단거리.py
BFS, DFS
레벨이 높아질수록,, 응용이 많아질수록 코딩력이 부족하다는 것을 뼈저리게 느낀 주였다
모르면 스트레스 받지 말고 검색하는것도 방법이다 세은아..!
> seeun-320 / 3주차 / 20문제

- BOJ/thing-zoo/week3/그림.py
- BOJ/thing-zoo/week3/나이트의 이동.py
- BOJ/thing-zoo/week3/다리 만들기.py
- BOJ/thing-zoo/week3/단지번호붙이기.py
- BOJ/thing-zoo/week3/말이 되고픈 원숭이.py
- BOJ/thing-zoo/week3/미로.py
- BOJ/thing-zoo/week3/벽 부수고 이동하기.py
- BOJ/thing-zoo/week3/벽 부수고 이동하기2.py
- BOJ/thing-zoo/week3/벽 부수고 이동하기3.py
- BOJ/thing-zoo/week3/불 켜기.py
- BOJ/thing-zoo/week3/불!(구글링).py
- BOJ/thing-zoo/week3/불!(실패).py
- BOJ/thing-zoo/week3/불.py
- BOJ/thing-zoo/week3/빙산.py
- BOJ/thing-zoo/week3/상범 빌딩.py
- BOJ/thing-zoo/week3/숨바꼭질.py
- BOJ/thing-zoo/week3/숨바꼭질3.py
- BOJ/thing-zoo/week3/숨바꼭질4.py
- BOJ/thing-zoo/week3/스타트링크.py
- BOJ/thing-zoo/week3/안전 영역.py
- BOJ/thing-zoo/week3/영역 구하기.py
- BOJ/thing-zoo/week3/유기농 배추.py
- BOJ/thing-zoo/week3/적록색약.py
- BOJ/thing-zoo/week3/텀 프로젝트.py
- BOJ/thing-zoo/week3/토마토.py
- BOJ/thing-zoo/week3/토마토2.py
- BOJ/thing-zoo/week3/확장 게임.py
- PGS/thing-zoo/코딩테스트 고득점 Kit/BFS, DFS/게임 맵 최단거리.py
- PGS/thing-zoo/코딩테스트 고득점 Kit/BFS, DFS/타겟 넘버.py
- 단어 변환.py
BFS, DFS
골드3부터 점점 구글링하지 않고는 풀지 못하기 시작했다....
문제 설명이 이해도 안되고 감도 안잡힘...
다시 한번 더 풀어야겠다...ㅎㅎ
> thing-zoo / 3주차 / 29문제

- BOJ/thing-zoo/5.백트랙킹/Gaaaaaaaaaarden.py
- BOJ/thing-zoo/5.백트랙킹/N-Queen.py
- BOJ/thing-zoo/5.백트랙킹/N과M(1).py
- BOJ/thing-zoo/5.백트랙킹/N과M(10).py
- BOJ/thing-zoo/5.백트랙킹/N과M(11).py
- BOJ/thing-zoo/5.백트랙킹/N과M(12).py
- BOJ/thing-zoo/5.백트랙킹/N과M(2).py
- BOJ/thing-zoo/5.백트랙킹/N과M(3).py
- BOJ/thing-zoo/5.백트랙킹/N과M(4).py
- BOJ/thing-zoo/5.백트랙킹/N과M(5).py
- BOJ/thing-zoo/5.백트랙킹/N과M(6).py
- BOJ/thing-zoo/5.백트랙킹/N과M(7).py
- BOJ/thing-zoo/5.백트랙킹/N과M(8).py
- BOJ/thing-zoo/5.백트랙킹/N과M(9).py
- BOJ/thing-zoo/5.백트랙킹/계란으로 계란치기.py
- BOJ/thing-zoo/5.백트랙킹/로또.py
- BOJ/thing-zoo/5.백트랙킹/부분수열의 합.py
- BOJ/thing-zoo/5.백트랙킹/비숍.py
- BOJ/thing-zoo/5.백트랙킹/소문난 칠공주.py
- BOJ/thing-zoo/5.백트랙킹/암호만들기.py
백트랙킹
백트랙킹은 쉽지만 문제는 코딩 센스가 필요해서..
문제를 더 열심히 풀어야겠다...하하...
> thing-zoo / 5주차 / 20문제 

- BOJ/seeun/11. 구현/11559_Puyo Puyo.py
- BOJ/seeun/11. 구현/13335_트럭.py
- BOJ/seeun/11. 구현/13460_구슬 탈출 2.py
- BOJ/seeun/11. 구현/14499_주사위 굴리기.py
- BOJ/seeun/11. 구현/14503_로봇 청소기.py
- BOJ/seeun/11. 구현/14888_연산자 끼워넣기.py
- BOJ/seeun/11. 구현/14889_스타트와 링크.py
- BOJ/seeun/11. 구현/14891_톱니바퀴.py
- BOJ/seeun/11. 구현/15686_치킨 배달.py
- BOJ/seeun/11. 구현/16234_인구 이동.py
- BOJ/seeun/11. 구현/16235_나무 재테크.py
- BOJ/seeun/11. 구현/17143_낚시왕.py
- BOJ/seeun/11. 구현/3190_뱀.py
구현..
어느 알고리즘을 사용한다기 보단 신박한 풀이가 필요한 문제들이라서 생각하는데 너무 힘들었다
> seeun-320 / 6주차 / 13문제

- BOJ/seeun/11. 구현/14500_테트로미노.py
- BOJ/seeun/11. 구현/14502_연구소.py
- BOJ/seeun/11. 구현/16236_아기 상어.py
- BOJ/seeun/11. 구현/17144_미세먼지 안녕.py
- BOJ/seeun/11. 구현/17281_⚾️.py
- BOJ/seeun/11. 구현/17822_원판 돌리기.py
- BOJ/seeun/12. 정렬/10814_나이순 정렬.py
- BOJ/seeun/12. 정렬/10989_수 정렬하기 3.py
- BOJ/seeun/12. 정렬/11651_좌표 정렬하기 2.py
- BOJ/seeun/12. 정렬/11652_카드.py
- BOJ/seeun/12. 정렬/11656_접미사 배열.py
- BOJ/seeun/12. 정렬/11931_수 정렬하기 4.py
- BOJ/seeun/12. 정렬/1431_시리얼 번호.py
- BOJ/seeun/12. 정렬/15688_수 정렬하기 5.py
- BOJ/seeun/12. 정렬/2750_수 정렬하기.py
- BOJ/seeun/12. 정렬/2751_수 정렬하기 2.py
- BOJ/seeun/12. 정렬/2910_빈도 정렬.py
- BOJ/seeun/12. 정렬/5648_역원소 정렬.py
- BOJ/seeun/12. 정렬/7795_먹을 것인가 먹힐 것인가.py
> seeun 320 / 7주차 / 19문제

- BOJ/thing-zoo/8.DP/1,2,3 더하기.py
- BOJ/thing-zoo/8.DP/1,2,3 더하기3.py
- BOJ/thing-zoo/8.DP/1로 만들기.py
- BOJ/thing-zoo/8.DP/1로 만들기2.py
- BOJ/thing-zoo/8.DP/2*n 타일링.py
- BOJ/thing-zoo/8.DP/2*n 타일링2.py
- BOJ/thing-zoo/8.DP/RGB거리.py
- BOJ/thing-zoo/8.DP/가장 긴 증가하는 부분 수열.py
- BOJ/thing-zoo/8.DP/가장 큰 증가하는 부분 수열.py
- BOJ/thing-zoo/8.DP/계단오르기.py
- BOJ/thing-zoo/8.DP/구간합 구하기4.py
- BOJ/thing-zoo/8.DP/쉬운 계단수.py
- BOJ/thing-zoo/8.DP/연속합.py
- BOJ/thing-zoo/8.DP/이친수.py
- BOJ/thing-zoo/8.DP/정수 삼각형.py
- BOJ/thing-zoo/8.DP/퇴사.py
- BOJ/thing-zoo/8.DP/퇴사2.py
- BOJ/thing-zoo/8.DP/파도반 수열.py
- BOJ/thing-zoo/8.DP/포도주 시식.py
- BOJ/thing-zoo/8.DP/피보나치 수2.py
- BOJ/thing-zoo/8.DP/피보나치 함수.py
DP
동적계획법은 마냥 어렵다고 생각했었는데 생각보다 풀만 했다.
물론 테이블을 짜는게 마냥 쉽진 않다ㅠㅠㅠㅜ 연습만이 살길..
> thing-zoo / 8주차 / 21문제 

- BOJ/thing-zoo/8.DP/극장 좌석.py
- BOJ/thing-zoo/8.DP/동전1.py
- BOJ/thing-zoo/8.DP/스티커.py
- BOJ/thing-zoo/8.DP/오르막수.py
- BOJ/thing-zoo/8.DP/자두나무.py
- BOJ/thing-zoo/8.DP/카드 구매하기.py
- BOJ/thing-zoo/8.DP/평범한 배낭.py
- BOJ/thing-zoo/9.그리디/ATM.py
- BOJ/thing-zoo/9.그리디/강의실 배정.py
- BOJ/thing-zoo/9.그리디/게임을 만든 동준이.py
- BOJ/thing-zoo/9.그리디/공주의 정원.py
- BOJ/thing-zoo/9.그리디/동전0.py
- BOJ/thing-zoo/9.그리디/뒤집기.py
- BOJ/thing-zoo/9.그리디/로프.py
- BOJ/thing-zoo/9.그리디/멀티탭 스케쥴링.py
- BOJ/thing-zoo/9.그리디/보물.py
- BOJ/thing-zoo/9.그리디/선긋기.py
- BOJ/thing-zoo/9.그리디/수 묶기.py
- BOJ/thing-zoo/9.그리디/잃어버린 괄호.py
- BOJ/thing-zoo/9.그리디/주식.py
- BOJ/thing-zoo/9.그리디/줄 세우기.py
- BOJ/thing-zoo/9.그리디/카드 합체 놀이.py
- BOJ/thing-zoo/9.그리디/택배.py
- BOJ/thing-zoo/9.그리디/회의실 배정.py
그리디
dp처럼 점화식을 찾아낼수도 없고 오로지 최적의 로직을 생각해내야하는 그리디..
막상 풀어보면 또 아주 간단한 로직이기도 해서 좀 허무했다ㅠ
많이 풀어서 생각하는 힘을 기를수밖에..
> thing-zoo / 9주차 / 24문제 

- BOJ/seeun/13. DP/1699_제곱수의 합.py
- BOJ/seeun/14. 그리디/11000_강의실 배정.py
- BOJ/seeun/14. 그리디/11047_동전 0.py
- BOJ/seeun/14. 그리디/11399_ATM.py
- BOJ/seeun/14. 그리디/11501_주식.py
- BOJ/seeun/14. 그리디/1541_잃어버린 괄호.py
- BOJ/seeun/14. 그리디/15903_카드 합체 놀이.py
- BOJ/seeun/14. 그리디/1700_멀티탭 스케줄링.py
- BOJ/seeun/14. 그리디/1744_수 묶기.py
- BOJ/seeun/14. 그리디/1931_회의실 배정.py
- BOJ/seeun/14. 그리디/2170_선 긋기.py
- BOJ/seeun/14. 그리디/2217_로프.py
- BOJ/seeun/14. 그리디/2457_공주님의 정원.py
- BOJ/seeun/14. 그리디/2847_게임을 만든 동준이.py
- BOJ/seeun/14. 그리디/7570_줄 세우기.py
- BOJ/seeun/14. 그리디/8980_택배.py
- PGS/seeun/코딩테스트 고득점 kit/탐욕법(Greedy)/체육복.py
> seeun 320 / 9주차 / 17문제

- BOJ/thing-zoo/10.수학/30.py
- BOJ/thing-zoo/10.수학/ACM호텔.py
- BOJ/thing-zoo/10.수학/GCD 합.py
- BOJ/thing-zoo/10.수학/LCM.py
- BOJ/thing-zoo/10.수학/거의 소수.py
- BOJ/thing-zoo/10.수학/골드바흐 파티션.py
- BOJ/thing-zoo/10.수학/골드바흐의 추측.py
- BOJ/thing-zoo/10.수학/날짜 계산.py
- BOJ/thing-zoo/10.수학/달팽이는 올라가고싶다.py
- BOJ/thing-zoo/10.수학/만취한 상범.py
- BOJ/thing-zoo/10.수학/벌집.py
- BOJ/thing-zoo/10.수학/베르트랑공준.py
- BOJ/thing-zoo/10.수학/분수찾기.py
- BOJ/thing-zoo/10.수학/설탕배달.py
- BOJ/thing-zoo/10.수학/소수 구하기.py
- BOJ/thing-zoo/10.수학/소수 찾기.py
- BOJ/thing-zoo/10.수학/소인수분해.py
- BOJ/thing-zoo/10.수학/수 복원하기.py
- BOJ/thing-zoo/10.수학/수학은 체육과목 입니다.py
- BOJ/thing-zoo/10.수학/에라토스테네스의 체.py
- BOJ/thing-zoo/10.수학/이항계수1.py
- BOJ/thing-zoo/10.수학/이항계수2.py
- BOJ/thing-zoo/10.수학/카잉달력.py
- BOJ/thing-zoo/10.수학/캠핑.py
- BOJ/thing-zoo/10.수학/팩토리얼 0의 개수.py
수학
초등학교 수학 경시대회 문제 느낌..? 오랜만에 수학 개념을 복습했습니다
> thing-zoo / 10주차 / 25문제 

- BOJ/seeun/15. 수학/10250_ACM 호텔.py
- BOJ/seeun/15. 수학/1038_감소하는 수.py
- BOJ/seeun/15. 수학/10610_30.py
- BOJ/seeun/15. 수학/11041_이항 계수 2.py
- BOJ/seeun/15. 수학/11653_소인수분해.py
- BOJ/seeun/15. 수학/1193_분수 찾기.py
- BOJ/seeun/15. 수학/1292_쉽게 푸는 문제.py
- BOJ/seeun/15. 수학/1456_거의 소수.py
- BOJ/seeun/15. 수학/1476_날짜 계산.py
- BOJ/seeun/15. 수학/15894_수학은 체육과목 입니다.py
- BOJ/seeun/15. 수학/1676_팩토리얼 0의 개수.py
- BOJ/seeun/15. 수학/17103_골드바흐 파티션.py
- BOJ/seeun/15. 수학/1735_분수 합.py
- BOJ/seeun/15. 수학/1929_소수 구하기.py
- BOJ/seeun/15. 수학/1978_소수 찾기.py
- BOJ/seeun/15. 수학/2004_조합 0의 개수.py
- BOJ/seeun/15. 수학/2312_수 복원하기.py
- BOJ/seeun/15. 수학/2839_설탕 배달.py
- BOJ/seeun/15. 수학/2869_달팽이는 올라가고 싶다.py
- BOJ/seeun/15. 수학/2960_에라토스테네스의 체.py
- BOJ/seeun/15. 수학/3036_링.py
- BOJ/seeun/15. 수학/4796_캠핑.py
- BOJ/seeun/15. 수학/4948_베르트랑 공준.py
- BOJ/seeun/15. 수학/5347_LCM.py
- BOJ/seeun/15. 수학/6064_카잉 달력.py
- BOJ/seeun/15. 수학/6359_만취한 상범.py
- BOJ/seeun/15. 수학/9020_골드바흐의 추측.py
- BOJ/seeun/15. 수학/9613_GCD 합.py
수학
수학적인 사고는 dp, 그리디 풀때보다 더 어려운듯 쉬운듯 하네요..
> seeun 320 / 10주차 / 28문제

- BOJ/seeun/16. 이분탐색/12015_가장 긴 증가하는 부분 수열 2.py
- BOJ/seeun/16. 이분탐색/7453_합이 0인 네 정수.py
- BOJ/seeun/17. 투 포인터/20366_같이 눈사람 만들래?.py
- BOJ/seeun/17. 투 포인터/20922_겹치는 건 싫어.py
- BOJ/seeun/17. 투 포인터/2283_구간 자르기.py
- BOJ/seeun/17. 투 포인터/22862_가장 긴 짝수 연속한 부분 수열 (large).py
- BOJ/seeun/17. 투 포인터/2461_대표 선수.py
- BOJ/seeun/17. 투 포인터/2531_회전 초밥.py
- BOJ/seeun/18. 해시/1351_무한 수열.py
- BOJ/seeun/18. 해시/1620_ 나는야 포켓몬 마스터 이다솜.py
- BOJ/seeun/19. 이진 검색 트리/7662_이중 우선순위 큐.py
해시, 이진검색트리, 투포인터, 이분탐색
이번주도 너무 쉬어버렸네요..
정신차리고 다시 공부를 해봅시다
> seeun 320 / 13주차 / 11문제

- BOJ/thing-zoo/16.그래프/11403-경로찾기/11403-1.py
- BOJ/thing-zoo/16.그래프/11403-경로찾기/11403-2.py
- BOJ/thing-zoo/16.그래프/11724-연결요소의 개수/11724.py
- BOJ/thing-zoo/16.그래프/1260-DFS와BFS/1260.py
- BOJ/thing-zoo/16.그래프/2606-바이러스/2606.py
- BOJ/thing-zoo/16.그래프/5567-결혼식/5567.py
그래프(BFS, 플루이드)
bfs를 이미 풀어봐서 어렵지 않았다.
> thing-zoo / 16주차 / 5문제 

- BOJ/seeun/21. 그래프/1043_거짓말.py
- BOJ/seeun/21. 그래프/11403_경로 찾기.py
- BOJ/seeun/21. 그래프/11724_연결 요소의 개수.py
- BOJ/seeun/21. 그래프/1260_DFS와 BFS.py
- BOJ/seeun/21. 그래프/1325_효율적인 해킹.py
- BOJ/seeun/21. 그래프/1389_케빈 베이컨의 6단계 법칙.py
- BOJ/seeun/21. 그래프/1707_이분 그래프.py
- BOJ/seeun/21. 그래프/2606_바이러스.py
- BOJ/seeun/21. 그래프/2617_구슬 찾기.py
- BOJ/seeun/21. 그래프/2660_회장뽑기.py
- BOJ/seeun/21. 그래프/5567_결혼식.py
- BOJ/seeun/21. 그래프/6118_숨바꼭질.py
- BOJ/seeun/22. 트리/11725_트리의 부모 찾기.py
- PGS/seeun/KAKAO BLIND RECRUITMENT/k진수에서 소수 개수 구하기.py
- PGS/seeun/KAKAO BLIND RECRUITMENT/두 큐 합 같게 만들기.py
- PGS/seeun/KAKAO BLIND RECRUITMENT/방금그곡.py
- PGS/seeun/KAKAO BLIND RECRUITMENT/오픈채팅방.py
- PGS/seeun/KAKAO BLIND RECRUITMENT/주차 요금 게산.py
- PGS/seeun/코딩테스트 고득점 kit/그래프/가장 먼 노드.py
그래프, 트리 한문제, 프로그래머스 카카오
다양한 알고리즘들을 공부를 좀 해야겠어요
> seeun 320 / 16주차 / 19문제

- BOJ/thing-zoo/16.그래프/1325-효율적인 해킹/1325.py
- BOJ/thing-zoo/16.그래프/1389-케빈 베이컨의 6단계 법칙/1389.py
- BOJ/thing-zoo/16.그래프/2660-회장뽑기/2660.py
- BOJ/thing-zoo/16.그래프/6118-숨바꼭질/6118.py
그래프
시간이 없어서 많이 못풀었다... 다음주부터는 꼭 5문제씩 풀도록 노력하겠다.....!
> thing-zoo / 17주차 / 4문제 

- BOJ/seeun/22. 트리/1068_트리.py
- BOJ/seeun/22. 트리/1240_노드사이의 거리.py
- BOJ/seeun/22. 트리/14267_회사 문화 1.py
- BOJ/seeun/22. 트리/15681_트리와 쿼리.py
- BOJ/seeun/22. 트리/1991_트리 순회.py
- BOJ/seeun/22. 트리/20955_민서의 응급 수술.py
- BOJ/seeun/22. 트리/2250_트리의 높이와 너비.py
- BOJ/seeun/22. 트리/4803_트리.py
- PGS/seeun/KAKAO BLIND RECRUITMENT/성격 유형 검사하기.py
- PGS/seeun/KAKAO BLIND RECRUITMENT/합승 택시 요금.py
- PGS/seeun/연습문제/쿠키 구입.py
트리, 카카오, 연습문제 등
대경권 .. 을 쳐보고 나의 수준을 다시 한 번 알게 되었다
> seeun 320 / 17주차 / 11문제

- BOJ/seeun/23. 위상 정렬/1005_ACM Craft.py
- BOJ/seeun/23. 위상 정렬/1766_문제집.py
- BOJ/seeun/23. 위상 정렬/2056_작업.py
- BOJ/seeun/23. 위상 정렬/21276_계보 복원가 호석.py
- BOJ/seeun/23. 위상 정렬/2252_줄 세우기.py
- BOJ/seeun/23. 위상 정렬/2623_음악프로그램.py
- BOJ/seeun/23. 위상 정렬/2637_장난감 조립.py
- PGS/seeun/KAKAO BLIND RECRUITMENT/다트 게임.py
- PGS/seeun/KAKAO BLIND RECRUITMENT/프렌즈4블록.py
위상정렬
이번주는 토스넥스트를 풀었다.. 코테 뿐만 아니라 디비나 다른 부분도 공부를 해야겠다..
> seeun 320 / 18주차 / 9문제

- BOJ/seeun/24. 최소 신장 트리/10423_전기가 부족해.py
- BOJ/seeun/24. 최소 신장 트리/1197_최소 스패닝 트리.py
- BOJ/seeun/24. 최소 신장 트리/13418_학교 탐방하기.py
- BOJ/seeun/24. 최소 신장 트리/1368_물대기.py
- BOJ/seeun/24. 최소 신장 트리/16398_행성 연결.py
- BOJ/seeun/24. 최소 신장 트리/1647_도시 분할 계획.py
- BOJ/seeun/24. 최소 신장 트리/1774_우주신과의 교감.py
- BOJ/seeun/24. 최소 신장 트리/2887_행성 터널.py
- BOJ/seeun/24. 최소 신장 트리/9372_상근이의 여행.py
- BOJ/seeun/25. 플로이드/11404_플로이드.py
- BOJ/seeun/25. 플로이드/11780_플로이드 2.py
최소 스패닝 트리
저번주는 약속 + 수련회로 문제를 풀지 못해서 월화수에 19주차 치를 벼락치기를 했다
옛날에 자료구조 배울 때 그래프 관련된 모든 알고리즘이 머리에서 뒤섞였었는데 그게 MST에 나오는거였다니
크루스칼, 프림 !!!
> seeun 320 / 19주차 / 11문제

- BOJ/seeun/11. 구현/10431.줄세우기.py
- BOJ/seeun/11. 구현/11723_집합.py
- BOJ/seeun/11. 구현/1205_등수 구하기.py
- BOJ/seeun/11. 구현/20056_마법사 상어와 파이어볼.py
- BOJ/seeun/11. 구현/20125_쿠키의 신체 측정.py
- BOJ/seeun/11. 구현/4659_비밀번호 발음하기.py
- BOJ/seeun/11. 구현/7568_덩치.py
- BOJ/seeun/11. 구현/8979_올림픽.py
- BOJ/seeun/15. 수학/13458_시험 감독.py
- BOJ/seeun/15. 수학/2292_벌집.py
- BOJ/seeun/15. 수학/23971_ZOAC 4.py
- BOJ/seeun/15. 수학/5073_삼각형과 세 변.py
- BOJ/seeun/18. 해시/25757_임스와 함께하는 미니게임.py
- PGS/seeun/KAKAO BLIND RECRUITMENT/파괴되지 않은 건물.py
- PGS/seeun/코딩테스트 고득점 kit/동적계획법/정수 삼각형.py
삼성 뽀개기
구현
독해 능력,, 문제 이해력 기르기..
아좌좌~!
> Seeun 320 / 코테준비 / 15문제

- BOJ/thing-zoo/10.수학/13458.py
- BOJ/thing-zoo/5.백트랙킹/19236.py
- BOJ/thing-zoo/6.구현, 시뮬레이션/16235.py
- BOJ/thing-zoo/6.구현, 시뮬레이션/17144.py
- BOJ/thing-zoo/6.구현, 시뮬레이션/19237.py
- BOJ/thing-zoo/6.구현, 시뮬레이션/20055.py
- BOJ/thing-zoo/6.구현, 시뮬레이션/20056.py
- BOJ/thing-zoo/6.구현, 시뮬레이션/20057.py
- BOJ/thing-zoo/6.구현, 시뮬레이션/20058.py
- BOJ/thing-zoo/6.구현, 시뮬레이션/21608.py
- BOJ/thing-zoo/6.구현, 시뮬레이션/21609.py
- BOJ/thing-zoo/6.구현, 시뮬레이션/21610.py
- BOJ/thing-zoo/6.구현, 시뮬레이션/21611.py
- BOJ/thing-zoo/6.구현, 시뮬레이션/23288.py
- BOJ/thing-zoo/6.구현, 시뮬레이션/23290.py
구현, 시뮬레이션, bfs
확실히 기출을 푸니까 점점 풀린다!
어제 삼성 코테에서 1번 문제는 비슷했고, 2번 문제는 스켈레톤 코드에 맞게 함수를 구현하는거였다.
2번 문제 풀려니 트리에다가 시간이 얼마없어서 그냥 나왔는데 다음에는 끝까지 풀어보자..
> thing-zoo / 삼성 코테 대비 / 15문제 

- BOJ/seeun/11. 구현/12100_2046(Easy).py
- BOJ/seeun/11. 구현/15683_감시.py
- BOJ/seeun/11. 구현/19236_청소년 상어.py
- BOJ/seeun/11. 구현/19237_어른 상어.py
- BOJ/seeun/11. 구현/19238_스타트 택시.py
- BOJ/seeun/11. 구현/20055_컨베이어 벨트 위의 로봇.py
- BOJ/seeun/11. 구현/20057_마법사 상어와 토네이도 .py
- BOJ/seeun/11. 구현/20058_마법사 상어와 파이어스톰.py
- BOJ/seeun/11. 구현/21608_상어 초등학교.py
- BOJ/seeun/11. 구현/21609_상어 중학교.py
- BOJ/seeun/11. 구현/21610_마법사 상어와 비바라기.py
- BOJ/seeun/11. 구현/21611_마법사 상어와 블리자드.py
- BOJ/seeun/11. 구현/23290_마법사 상어와 복제.py
- BOJ/seeun/14. 그리디/1689_겹치는 선분.py
- BOJ/seeun/14. 그리디/1931_회의실 배정(LG기원).py
- BOJ/seeun/14. 그리디/1946_신입 사원.py
- BOJ/seeun/14. 그리디/2821_크게 만들기.py
- BOJ/seeun/15. 수학/1834_나머지와 몫이 같은 수.py
- BOJ/seeun/4. 스택/17298_오큰수(LG기원).py
삼성: 구현, 시뮬레이션
LG: 스택, 그리디
두 회사의 문제 유형이 너무 달라서 머리가 혼란스럽지만 화이팅~
> Seeun 320 / 코테 대비 / 삼성 13문제 + LG 6문제

- BOJ/seeun/10. 백트래킹/10819_차이를 최대로.py
- BOJ/seeun/10. 백트래킹/15649_N과 M (1)(LG기원).py
- BOJ/seeun/10. 백트래킹/2529_부등호.py
- BOJ/seeun/11. 구현/1157_단어 공부.py
- BOJ/seeun/11. 구현/1236_성 지키기.py
- BOJ/seeun/11. 구현/1268_임시 반장 정하기.py
- BOJ/seeun/11. 구현/1296_팀 이름 정하기.py
- BOJ/seeun/11. 구현/1357_뒤집힌 덧셈.py
- BOJ/seeun/13. DP/2156_포도주 시식(LG기원).py
- BOJ/seeun/13. DP/2579_계단 오르기(LG기원).py
- BOJ/seeun/14. 그리디/1461_도서관.py
- BOJ/seeun/15. 수학/1292_쉽게 푸는 문제(LG기원).py
- BOJ/seeun/15. 수학/2839_설탕 배달(LG기원).py
- BOJ/seeun/3. 연결리스트/1406_에디터(LG기원).py
- BOJ/seeun/4. 스택/9935_문자열 폭발.py
- BOJ/seeun/5. 스택의 활용/10799_쇠막대기.py
- BOJ/seeun/5. 스택의 활용/4949_균형잡힌 세상(LG기원).py
- BOJ/seeun/8. BFS, DFS/1987_알파벳(LG기원).py
- PGS/seeun/연습문제/공원 산책.py
- PGS/seeun/연습문제/달리기 경주.py
- PGS/seeun/연습문제/바탕화면 정리.py
- PGS/seeun/연습문제/요격 시스템.py
- PGS/seeun/코딩테스트 고득점 kit/BFS, DFS/여행경로.py
- PGS/seeun/코딩테스트 고득점 kit/정렬/H-Index.py
- PGS/seeun/코딩테스트 고득점 kit/해시/베스트앨범.py
- PGS/seeun/코딩테스트 고득점 kit/해시/의상.py
스택, 그리디, dp, 백트래킹 등 LG 기출 알고리즘 위주
그리디가 그렇게 어려웠는데 안나와서 다행이었다..
하지만 앞으로 극복할 수 있도록.. 공부할 것,,
> Seeun 320 / LG 대비 / 26문제

- BOJ/seeun/11. 구현/21921_블로그.py
- BOJ/seeun/11. 구현/9017_크로스 컨트리.py
- BOJ/seeun/16. 이분탐색/17266_어두운 굴다리.py
IT, 대기업 코테 문제집
넘혜브냉 자소서 쓰고 의성가서 쉬느라 이것밖에 못풀었다
이번주 부터 다시.. 아자.. ,,!
> Seeun 320 / 넘예브넹 / 3문제

- BOJ/seeun/4. 스택/2304_창고 다각형.py
- BOJ/seeun/5. 스택의 활용/2504_괄호의 값.py
- SFT/seeun/8단 변속기.py
- SFT/seeun/A+B.py
- SFT/seeun/강의실 배정.py
- SFT/seeun/금고털이(다시품).py
- SFT/seeun/동계 테스트 시점 예측.py
- SFT/seeun/바이러스.py
- SFT/seeun/성적 평균.py
- SFT/seeun/우물 안 개구리.py
- SFT/seeun/장애물 인식 프로그램.py
- SFT/seeun/조립라인.py
- SFT/seeun/징검다리.py
현대오토에버 대비 + IT/대기업 문제집
현대오토에버는 갑작스러운 accident로 인해 집중하지 못하고.. 시간초과로 2문제 날린 것 같다. 1솔..?인듯
올해 거의 마지막 코테였는데......
> Seeun 320 / 현대오토에버 대비 / 13문제

- BOJ/thing-zoo/13.해시/문자열 집합.py
- BOJ/thing-zoo/13.해시/부품대여장.py
- BOJ/thing-zoo/13.해시/생태학.py
- BOJ/thing-zoo/15.우선순위큐/2696-중앙값 구하기/중앙값 구하기.py
- BOJ/thing-zoo/15.우선순위큐/2696-중앙값 구하기/중앙값 구하기2.py
- BOJ/thing-zoo/15.우선순위큐/문제 추천 시스템 Version 1.py
- BOJ/thing-zoo/2.덱/풍선 터뜨리기.py
- BOJ/thing-zoo/2.스택/1874-스택 수열/1874.py
- BOJ/thing-zoo/2.스택/탑.py
- BOJ/thing-zoo/2.스택의 활용/22942-데이터 체커/데이터 체커.py
- BOJ/thing-zoo/2.스택의 활용/22942-데이터 체커/데이터체커-2.py
- BOJ/thing-zoo/2.스택의 활용/괄호의 제거.py
- BOJ/thing-zoo/2.스택의 활용/후위 표기식.py
- BOJ/thing-zoo/2.스택의 활용/후위표기식2.py
- BOJ/thing-zoo/2.큐/프린터 큐.py
- PGS/thing-zoo/2018 KAKAO BLIND RECRUITMENT/[1차] 비밀지도.py
- PGS/thing-zoo/2018 KAKAO BLIND RECRUITMENT/[1차] 캐시.py
- PGS/thing-zoo/2019 카카오 개발자 겨울 인턴십/튜플.py
- PGS/thing-zoo/2021 Dev-Matching: 웹 백엔드 개발자(상반기)/헤비 유저가 소유한 장소.sql
- PGS/thing-zoo/2021 카카오 채용연계형 인턴십/숫자 문자열과 영단어.py
- PGS/thing-zoo/2023 KAKAO BLIND RECRUITMENT/개인정보수집 유효기간.py
- PGS/thing-zoo/코딩테스트 고득점 Kit/그리디/조이스틱.py
> thing-zoo / 코테 대비 / 7문제

- BOJ/seeun/11. 구현/5597_과제 안 내신 분..?.py
- BOJ/seeun/15. 수학/5618_공약수.py
- BOJ/seeun/18. 해시/ 4358_생태학.py
- BOJ/seeun/18. 해시/14425_문자열 집합.py
- BOJ/seeun/18. 해시/20291_파일 정리.py
- BOJ/seeun/20. 우선순위 큐/2696_중앙값 구하기.py
- BOJ/seeun/22. 트리/9934_완전 이진 트리.Py
- BOJ/seeun/5. 스택의 활용/1918_후위 표기식.py
- BOJ/seeun/5. 스택의 활용/1935_후위 표기식2.py
- BOJ/seeun/5. 스택의 활용/2800_괄호 제거.py
- BOJ/seeun/6. 큐/1966_프린터 큐.py
- BOJ/seeun/7. 덱/2346_풍선 터뜨리기.py
> Seeun 320 /  1월 1~3주차 / 12문제

- BOJ/seeun/13. DP/10870_피보나치 수 5.py
- BOJ/seeun/15. 수학/22864_피로도.py
> Seeun 320 / 1월 4주차 / 2문제

- BOJ/seeun/13. DP/14916_거스름돈.py
- BOJ/seeun/15. 수학/21312_홀짝 칵테일.py
- BOJ/seeun/17. 투 포인터/15565_귀여운 라이언.py
- BOJ/seeun/17. 투 포인터/2470_두 용액.py
- BOJ/seeun/18. 해시/21942_부품 대여장.Py
- BOJ/seeun/21. 그래프/16918_봄버맨.py
- BOJ/seeun/26. 다익스트라/18352_특정 거리의 도시 찾기.py
- BOJ/seeun/8. BFS, DFS/17836_공주님을 구해라!.py
투포인터, 해시, 그래프, 디피 등..
현토에버 대비로 그냥 풀고싶은 부분만 듬성듬성 풀었습니다요
> Seeun 320 / 2월 1주차 / 8문제

- BOJ/thing-zoo/02.스택/도키도키 간식드리미.py
- BOJ/thing-zoo/08.DP/1,2,3 더하기.py
- BOJ/thing-zoo/08.DP/2*n 타일링.py
- BOJ/thing-zoo/08.DP/Four Squares.py
- BOJ/thing-zoo/08.DP/가장 긴 증가하는 부분 수열.py
- BOJ/thing-zoo/08.DP/계단오르기.py
- BOJ/thing-zoo/08.DP/다리 놓기.py
- BOJ/thing-zoo/08.DP/돌게임.py
- BOJ/thing-zoo/08.DP/설탕 배달.py
- BOJ/thing-zoo/08.DP/조합.py
- BOJ/thing-zoo/08.DP/피보나치 수 5.py
- BOJ/thing-zoo/11.이분탐색/가장 긴 증가하는 부분 수열2.py
- SFT/thing-zoo/lv2/연탄의 크기.py
- SFT/thing-zoo/lv2/진정한 효도.py
- SFT/thing-zoo/lv3/GINI야 도와줘.py
- SFT/thing-zoo/lv3/나무조경.py
- SFT/thing-zoo/lv3/로봇이 지나간 경로.py
- SFT/thing-zoo/lv3/염기서열 커버.py
- SFT/thing-zoo/lv3/좌석 관리.py
- SFT/thing-zoo/lv3/택배 마스터 광우.py
- SFT/thing-zoo/lv3/플레이페어.py
DP, 현토에버 코테 대비
제가 가장 약한 DP부터 공부했습니다..!
또 풀어도 또 틀리는 문제도 있고,,,ㅎ
기억이 나서 금방 푸는 문제도 있네용..흑흑
좀 더 풀어봐야겠어요...
> thing-zoo / 2월 1주차 / 21문제 

- BOJ/seeun/11. 구현/1212_8진수 2진수.py
- BOJ/seeun/11. 구현/14719_빗물.py
- BOJ/seeun/11. 구현/17135_캐슬 디펜스.py
- BOJ/seeun/13. DP/1915_가장 큰 정사각형.py
- BOJ/seeun/13. DP/2225_합분해.py
- BOJ/seeun/13. DP/2294_동전 2.py
- BOJ/seeun/14. 그리디/11256_사탕.py
- BOJ/seeun/14. 그리디/20115_에너지 드링크.py
- BOJ/seeun/15. 수학/1267_핸드폰 요금.py
- BOJ/seeun/15. 수학/14929_귀찮아 (SIB).py
- BOJ/seeun/17. 투 포인터/11728_배열 합치기.py
- BOJ/seeun/21. 그래프/14940_쉬운 최단거리.py
- BOJ/seeun/5. 스택의 활용/22942_데이터 체커.py
구현, DP, 그리디, 수학, 투포인터, 그래프, 스택
정신을 차리고자 했지만 밀려드는 자소서에 정신을 차리지 못하고 또,,,
막주에 최대한 하루에 한문제 풀어보려고 노력은 해봤습니다 🥹
> Seeun 320 / 3월 2주차 ~ 3월 4주차 / 13문제

- BOJ/thing-zoo/08.DP/징검다리 건너기(small).py
- BOJ/thing-zoo/08.DP/징검다리 건너기.py
- BOJ/thing-zoo/08.DP/퇴사2.py
- BOJ/thing-zoo/09.그리디/꿀 따기.py
- BOJ/thing-zoo/09.그리디/우체국.py
- PGS/thing-zoo/SQL 고득점 Kit/JOIN/주문량이 많은 아이스크림들 조회하기.sql
- PGS/thing-zoo/SQL 고득점 Kit/JOIN/특정 기간동안 대여 가능한 자동차들의 대여비용 구하기.sql
그리디, DP, SQL
취약한 그리디부분을 풀어 보았습니다..여전히 취약합니다 ㅎ
자소서 쓰느라 너무 못풀었네요 저도 이제 힘내보겠습니당!
> thing-zoo / 3월 2~4주차 / 7 문제 

- BOJ/seeun/11. 구현/1259_팰린드롬수.py
- BOJ/seeun/11. 구현/16926_배열 돌리기 1.py
- BOJ/seeun/11. 구현/16935_배열 돌리기 3.py
- BOJ/seeun/11. 구현/17276_배열 돌리기.py
- BOJ/seeun/11. 구현/17406_배열 돌리기 4.py
구현
배열 돌리기의 달인이 되는 중입니다
구현 재밌네요..
다른 알고리즘 싫어~ㅠ
> Seeun 320 / 4월 1주차 / 5문제

- BOJ/thing-zoo/06.구현, 시뮬레이션/8진수 2진수.py
- BOJ/thing-zoo/06.구현, 시뮬레이션/과제 안 내신 분..?.py
- BOJ/thing-zoo/06.구현, 시뮬레이션/기적의 매매법.py
- BOJ/thing-zoo/06.구현, 시뮬레이션/배열 돌리기.py
- BOJ/thing-zoo/06.구현, 시뮬레이션/소가 길을 건너간 이유1.py
- BOJ/thing-zoo/06.구현, 시뮬레이션/전구.py
- BOJ/thing-zoo/06.구현, 시뮬레이션/최소, 최대2.py
- BOJ/thing-zoo/08.DP/주지수.py
- BOJ/thing-zoo/12.투포인터/배열 합치기.py
구현, DP, 투포인터
이제부터 다양하게 풀어보려고 합니당..!
> thing-zoo / 4월 1주차 / 9 문제

- BOJ/seeun/13. DP/15624_피보나치 수 7.py
- BOJ/seeun/13. DP/15990_1, 2, 3 더하기 5.py
- BOJ/seeun/13. DP/17626_Four Squares.py
- BOJ/seeun/13. DP/2491_수열.py
- BOJ/seeun/14. 그리디/2141_우체국.py
그리디, dp
정처기에 치여 4주차는 풀지 못했습니다.. 다시 시작...
> Seeun 320 / 4월 3주차 / 5문제
